modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_source}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "logo.png"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${supported_minecraft_version_neoforge}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "cloth_config"
type = "optional"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"